### ISSUE TITLE
Package missing from Repo

### ISSUE THREAD

**Issue by dobbleg1000** [negativo17/radarr-selinux#1]
the rpm is missing from https://negativo17.org/repos/multimedia/fedora-34/x86_64/
And i am unable to reinstall.

**Comment by scaronni** [comment]
Coming in a few minutes.. I have a weird issue with a drive in an array, it was corrupting files under heavy I/O, but it was never marked as failed. It took me a while to figure out, unfortunately by then many packages got corrupted, so I had to rebuild most of the ones in the multimedia repository.

`x86_64` is done, `aarch64` is almost done.
